# Generated by Django 5.0.3 on 2024-04-03 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Mr', 'Mr'), ('Ms', 'Ms'), ('Mrs', 'Mrs')], max_length=3)),
                ('date_of_birth', models.DateField()),
                ('passport_number', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='booking',
            name='seat_class',
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('CNL', 'Canceled'), ('PPD', 'Postponed'), ('CMP', 'Completed')], default='PPD', max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='trip_type',
            field=models.CharField(choices=[('OW', 'One Way'), ('RT', 'Round Trip')], default='OW', max_length=10),
        ),
        migrations.CreateModel(
            name='Baggage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baggage_type', models.CharField(choices=[('HI', 'Hand Item'), ('PI', 'Personal Item'), ('CB', 'Checked Baggage')], default='HI', max_length=2)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baggages', to='booking.passenger')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='Passenger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.passenger'),
        ),
    ]
