# Generated by Django 5.0.3 on 2024-04-03 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_passenger_remove_booking_seat_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
