# Generated by Django 5.0.3 on 2024-04-08 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_booking_booking_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='Passenger',
            new_name='passenger',
        ),
    ]
