# Generated by Django 5.0.3 on 2024-03-30 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='has_companions',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Companion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Mr', 'Mr'), ('Ms', 'Ms')], max_length=2)),
                ('passport_number', models.CharField(max_length=20)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companions', to='booking.booking')),
            ],
        ),
    ]
