# Generated by Django 5.0.3 on 2024-03-30 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_booking_has_companions_companion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companion',
            name='gender',
            field=models.CharField(choices=[('Mr', 'Mr'), ('Ms', 'Ms'), ('Mrs', 'Mrs')], max_length=3),
        ),
    ]
