# Generated by Django 5.0.3 on 2024-04-10 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_pushnotificationtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='passenger',
        ),
        migrations.AddField(
            model_name='booking',
            name='Passenger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.passenger'),
        ),
    ]
