# Generated by Django 5.0.3 on 2024-04-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_remove_booking_passenger_booking_passenger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushnotificationtoken',
            name='fcm_token',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
