# Generated by Django 5.0.3 on 2024-04-12 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_pushnotificationtoken_fcm_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PushNotificationToken',
        ),
    ]
