# Generated by Django 5.0.3 on 2024-04-01 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_companion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Companion',
        ),
    ]
