# Generated by Django 5.0.3 on 2024-04-01 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_delete_companion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baggage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('SM', 'Small'), ('LG', 'Large')], max_length=2)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baggages', to='booking.passenger')),
            ],
        ),
    ]
